{% set name = "tfv" %}
{% set version = "1.0.14" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tfv-{{ version }}.tar.gz
  sha256: 3563573d16b51e3ddf40da7dab0ac6965cf3980aa9bed5e7631bd35f048ff8c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.24.0
    - matplotlib-base >=3.7.0
    - netcdf4 >=1.6.3
    - xarray >=2023.1.0
    - dask-core >=2023.1.0
    - scipy >=1.10.0
    - tqdm >=4.65.0
    - pyproj >=3.5.0
    - geopandas >=0.13.0
    - shapely >=2.0.0
    - rioxarray >=0.13.0
    - ipywidgets >=8.0.0
    - ipympl >=0.9.0
    - wheel

test:
  imports:
    - tfv
  commands:
    - pip check
    - pytest ./tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/
    - tfv/

about:
  home: https://gitlab.com/tuflow-user-group/tuflow-fv/tfv
  summary: Post processing tools for TUFLOW FV results
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TUFLOW-Support
    - Mitch3007
    - jaapvandervelde-tuflow
